# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
torch_dtype: null
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  princeton-nlp/llama3-ultrafeedback-armorm: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# AlphaDPOTrainer arguments
bf16: true
beta: 10
gamma_beta_ratio: 0.4
alpha: 0.2
ln: true
trainer_type: dpo
loss_type: alpha-dpo
do_eval: true
evaluation_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 16 
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: alpha-dpo-exps
learning_rate: 1.0e-6
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
output_dir: outputs/llama-3-8b-instruct-alpha-dpo-v2
run_name: llama-3-8b-instruct-alpha-dpo-v2
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
